import Header from '@/components/header';
import { authOptions } from '@/server/auth';
import { type GetServerSidePropsContext } from 'next';
import { getServerSession } from 'next-auth';
import { useSession } from 'next-auth/react';
import Head from 'next/head';

export default function NTPAuthenticated() {
	const session = useSession();

	return (
		<>
			<Head>
				<title>NTP Authentication</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="h-screen">
				<Header title="NTP Authentication" session={session.data} />
				<div className="fixed flex flex-col h-full w-full items-center justify-center gap-3">
					<h1 className="text-2xl font-bold tracking-tight">
						Not NTP Authenticated
					</h1>
					<p className="text-sm text-muted-foreground">
						You must be <b className="underline">authenticated</b> with NTP to
						gain access.
					</p>
				</div>
			</main>
		</>
	);
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
	const session = await getServerSession(context.req, context.res, authOptions);

	if (session?.user.ntpAuthenticated) {
		return {
			redirect: {
				destination: '/home',
				permanent: false,
			},
		};
	}

	return {
		props: {
			session,
		},
	};
}
