import { type GetServerSidePropsContext, type NextPage } from 'next';
import Head from 'next/head';
import Header from '@/components/header';
import { Toaster } from '@/components/ui/toaster';
import { ntpProtectedRoute } from '@/lib/protectedRoute';
import { useSession } from 'next-auth/react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { LucideRotate3d, LucideShare2 } from 'lucide-react';

const Home: NextPage = () => {
	const session = useSession();

	return (
		<>
			<Head>
				<title>NTP Home</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex h-screen">
				<Header title="Welcome" session={session.data} />
				<Toaster />
				<div className="container flex items-center ">
				<div className="container flex flex-col items-start justify-start p-6 space-y-10">
					<div className="text-6xl">
						<span className="font-bold">NTP</span> Insights
					</div>
					 <h3 className=" text-2xl font-semibold">v1.0</h3> {/* TODO: Get version number from GitHub */}
					<div className="flex flex-row items-start space-x-4">
						<Link href="/social/dashboard">
							<Button className="flex flex-row space-x-2">
								<LucideShare2 />
								<p>Social</p>
							</Button>
						</Link>
						<Link href="/360/dashboard">
							<Button className="flex flex-row space-x-2">
								<LucideRotate3d />
								<p>360</p>
							</Button>
						</Link>
					</div>
				</div>
				</div>
			</main>
		</>
	);
};

export default Home;

export async function getServerSideProps(context: GetServerSidePropsContext) {
	return await ntpProtectedRoute(context);
}
