import { type NextPage } from 'next';
import getConfig from 'next/config';
import Head from 'next/head';
import Link from 'next/link';
import Header from '@/components/header';
import { Toaster } from '@/components/ui/toaster';
import { useSession } from 'next-auth/react';
import { Button } from '@/components/ui/button';
import { LucideRotate3d, LucideShare2, LucideAxis3d } from 'lucide-react';
import Image from 'next/image';

const Home: NextPage = () => {
	const session = useSession();
	const { publicRuntimeConfig } = getConfig();

	return (
		<>
			<Head>
				<title>NTP Insights Home</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="bg-hero bg-[url('https://www.uwo.ca/ntp/img/bnr-tornado.jpg')] bg-cover bg-fixed bg-center bg-no-repeat">
				<div className="bg-gradient-to-r from-[background]">
					<main className="flex h-screen">
						<Header session={session.data} />
						<Toaster />
						<div className="absolute bottom-0 right-0 m-4">
							<Image
								width={150}
								height={200}
								alt="Western Engineering"
								src="/weng.png"
							/>
						</div>
						<div className="container flex flex-col justify-center space-y-1 p-6">
							<div className="py-4 text-7xl">
								<br />
								<span className="font-bold">NTP</span> Insights
							</div>
							<h3 className="py-4 text-2xl font-semibold">{`v${publicRuntimeConfig?.version}`}</h3>
							<div className="flex flex-row items-start space-x-4 py-4">
								<Link href="/social/dashboard">
									<Button className="flex flex-row space-x-2">
										<LucideShare2 />
										<p>Social</p>
									</Button>
								</Link>
								<Link href="/360/dashboard">
									<Button className="flex flex-row space-x-2">
										<LucideRotate3d />
										<p>360</p>
									</Button>
								</Link>
								<Link href="/lidar/dashboard">
									<Button className="flex flex-row space-x-2">
										<LucideAxis3d />
										<p>LiDAR</p>
									</Button>
								</Link>
							</div>
						</div>
					</main>
				</div>
			</div>
		</>
	);
};

export default Home;