import { Button } from '@/components/ui/button';
import { authOptions } from '@/server/auth';
import { type GetServerSidePropsContext } from 'next';
import { getServerSession } from 'next-auth';
import { signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function NTPAuthenticated() {
	const session = useSession();
	const router = useRouter();

	const handleSignOut = async () => {
		const data = await signOut({
			redirect: false,
			callbackUrl: '/',
		});
		await router.push(data.url);
	};

	return (
		<>
			<Head>
				<title>NTP Authentication</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex h-screen flex-col items-center justify-center">
				<div className="flex flex-col items-center justify-center gap-12 px-4 py-16 md:w-[356px]">
					<div className="flex flex-col gap-2 text-center">
						<h1 className="text-2xl font-bold tracking-tight">
							Not NTP Authenticated
						</h1>
						<p className="text-sm text-muted-foreground">
							You must be authenticated with NTP to gain access.
						</p>
						<h2 className="pt-8 text-xl">
							Current status:{' '}
							{session.data?.user.ntpAuthenticated ? (
								<p className="font-bold text-success">Authenticated</p>
							) : (
								<p className="font-bold text-destructive">Not Authenticated</p>
							)}
						</h2>
						<Button className="mt-8" onClick={() => void handleSignOut()}>
							Sign-out
						</Button>
					</div>
				</div>
			</main>
		</>
	);
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
	const session = await getServerSession(context.req, context.res, authOptions);

	if (session?.user.ntpAuthenticated) {
		return {
			redirect: {
				destination: '/dashboard',
				permanent: false,
			},
		};
	}

	return {
		props: {
			session,
		},
	};
}
