import { type GetServerSidePropsContext, type NextPage } from 'next';
import Head from 'next/head';
import Header from '@/components/header';
import { Toaster } from '@/components/ui/toaster';
import { OrbitControls } from '@react-three/drei'
import { ntpProtectedRoute } from '@/lib/protectedRoute';
import { useSession } from 'next-auth/react';
import { Canvas, useFrame, useLoader, useThree } from '@react-three/fiber';
import * as THREE from 'three';
import { Suspense } from 'react';

function StreetViewImage() {
	const texture = useLoader(THREE.TextureLoader, './Street_View_360.jpg');
	texture.mapping = THREE.EquirectangularReflectionMapping;
	texture.minFilter = texture.magFilter = THREE.LinearFilter;
	return (
		<mesh>
			<sphereGeometry attach="geometry" args={[500, 60, 40]} />
			<meshBasicMaterial attach="material" map={texture} side={THREE.BackSide} />
		</mesh>
	)
}

function Controls() {
	const { camera, gl } = useThree();

	useFrame(() => {
		camera.updateProjectionMatrix();
	});

	return <OrbitControls target={[0, 0, 0]} autoRotate rotateSpeed={-0.5} args={[camera, gl.domElement]} />
}

const Example: NextPage = () => {
	const session = useSession();

	return (
		<>
			<Head>
				<title>NTP 360</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="h-screen">
				<Header title={
					<>
						NTP{" "}<span className='text-success'>360</span>
					</>
				} session={session.data} />
				<Toaster />
				<div className="container flex flex-col items-center justify-center p-6">
					<div className='h-[600px] w-full p-2'>
						<Canvas camera={{ position: [0, 0, 0] }}>
							<Controls />
							<Suspense fallback={null}>
								<StreetViewImage />
							</Suspense>
						</Canvas>
					</div>
				</div>
			</main>
		</>
	);
};

export default Example;

export async function getServerSideProps(context: GetServerSidePropsContext) {
	return await ntpProtectedRoute(context);
}
