import { type GetServerSidePropsContext, type NextPage } from 'next';
import Head from 'next/head';
import Header from '@/components/header';
import { Toaster } from '@/components/ui/toaster';
import { ntpProtectedRoute } from '@/lib/protectedRoute';
import { useSession } from 'next-auth/react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { LucideRotate3d, LucideShare2 } from 'lucide-react';

const Home: NextPage = () => {
	const session = useSession();

	return (
		<>
			<Head>
				<title>NTP Insights</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="h-screen">
				<Header
					title={
						<>
							NTP <span className="font-medium">Insights</span>
						</>
					}
					session={session.data}
				/>
				<Toaster />
				<div className="container flex flex-col items-center justify-center space-y-4 p-6">
					<Link href="/social/dashboard">
						<Button className="flex flex-row space-x-2">
							<LucideShare2 />
							<p>Social</p>
						</Button>
					</Link>
					<Link href="/360/dashboard">
						<Button className="flex flex-row space-x-2">
							<LucideRotate3d />
							<p>360</p>
						</Button>
					</Link>
				</div>
			</main>
		</>
	);
};

export default Home;

export async function getServerSideProps(context: GetServerSidePropsContext) {
	return await ntpProtectedRoute(context);
}
