import { type NextPage } from 'next';
import Head from 'next/head';
import Header from '@/components/header';
import { Toaster } from '@/components/ui/toaster';
import { useSession } from 'next-auth/react';
import { View360 } from '@/components/view-360';
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from '@/components/ui/card';
import { View360Map } from '@/components/map';
import { LngLat } from 'mapbox-gl';
import { useRouter } from 'next/router';

const View: NextPage = () => {
	const session = useSession();
	const router = useRouter();
	const {
		id,
	}: {
		id?: string;
	} = router.query;

	const points = [
		LngLat.convert({
			lng: -81.2728488,
			lat: 43.00762673,
		}),
		LngLat.convert({
			lng: -81.27286469,
			lat: 43.00763391,
		}),
		LngLat.convert({
			lng: -81.27280041,
			lat: 43.00765001,
		}),
	];

	return (
		<>
			<Head>
				<title>{id ? `NTP 360 | ${id}` : 'NTP 360'}</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="h-screen">
				<Header
					title={
						<>
							NTP <span className="text-success">360</span>
						</>
					}
					session={session.data}
				/>
				<Toaster />
				<div className="container flex flex-col items-center justify-center p-6">
					<h2 className="mb-4 flex w-full flex-row items-center gap-4 text-left text-2xl font-medium">
						{id}
					</h2>
					<div className="grid w-full grid-cols-1 gap-4 lg:grid-cols-5 lg:grid-rows-2">
						<View360 className="relative row-span-3 h-[500px] overflow-hidden rounded-md lg:col-span-4 lg:h-[515px]" />
						<Card className="lg:row-span-1">
							<CardHeader>
								<CardTitle>Details</CardTitle>
								<CardDescription>About the current 360 view.</CardDescription>
								<br />
								<CardContent className="p-0">
									<CardDescription>Located at</CardDescription>
									<p>
										{points[0]?.lng}, {points[0]?.lat}
									</p>
									<br />
									<CardDescription>Previous location</CardDescription>
									<p>
										{points[points.length - 1]?.lng},{' '}
										{points[points.length - 1]?.lat}
									</p>
									<br />
									<CardDescription>Panorama capture</CardDescription>
									<p>1 / 203</p>
								</CardContent>
							</CardHeader>
						</Card>
						<div className="col-span-1 lg:row-span-1 ">
							<View360Map
								points={points}
								className="h-[400px] overflow-hidden rounded-md lg:h-40"
							/>
						</div>
					</div>
				</div>
			</main>
		</>
	);
};

export default View;
