import type { GetServerSidePropsContext, NextPage } from 'next';
import Head from 'next/head';
import Header from '@/components/header';
import { Toaster } from '@/components/ui/toaster';
import { useSession } from 'next-auth/react';
import {
	columns,
	paths,
} from '../../components/data-tables/paths/columns';
import { DataTable } from '@/components/data-tables/paths/data-table';
import { NewPathDialog } from '@/components/dialogs/new-path-dialog';
import { ntpProtectedRoute } from '@/lib/protectedRoute';

const Dashboard: NextPage = () => {
	const session = useSession();

	return (
		<>
			<Head>
				<title>NTP 360</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="h-screen">
				<Header
					title={
						<p>
							NTP <span className="text-success">360</span>
						</p>
					}
					session={session.data}
				/>
				<Toaster />
				<div className="container flex flex-col p-6">
					<div className="flex flex-row items-center space-x-4 pb-6">
						<h3 className="text-2xl font-semibold tracking-tight">Paths</h3>
						<NewPathDialog />
					</div>
					<DataTable columns={columns} data={paths} />
				</div>
			</main>
		</>
	);
};

export default Dashboard;

export async function getServerSideProps(context: GetServerSidePropsContext) {
	return await ntpProtectedRoute(context);
}
