import { GetServerSidePropsContext, type NextPage } from 'next';
import Head from 'next/head';
import Header from '@/components/header';
import { Toaster } from '@/components/ui/toaster';
import { useSession } from 'next-auth/react';
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from '@/components/ui/card';
import { Upload, columns, uploads } from "./columns"
import { DataTable } from "./data-table"
import { View360Map } from '@/components/map';
import { LngLat } from 'mapbox-gl';
import { New360ViewDialog } from '@/components/new-360-view-dialog';
import ServerStatusBadge from '@/components/server-status-badge';
import { ntpProtectedRoute } from '@/lib/protectedRoute';

const Dashboard: NextPage = () => {
    const session = useSession();

    return (
        <>
        <Head>
			<title>NTP 360</title>
			<meta name="description" content="Generated by create-t3-app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<main className="h-screen">
			<Header
				title={
					<>
						NTP <span className="text-success">360</span>
					</>
				}
				session={session.data}
			/>
			<Toaster />
			<div className="container flex flex-col items-center justify-center p-6">
                <DataTable columns={columns} data={uploads} />
			</div>
			</main>
		</>
    );
};

export default Dashboard;

export async function getServerSideProps(context: GetServerSidePropsContext) {
	return await ntpProtectedRoute(context);
}