import Head from 'next/head';
import { NextPage } from 'next';
import dynamic from 'next/dynamic';
import { Canvas } from '@react-three/fiber';
import { PotreeDetails } from '@/components/potree-details';
import Header from '@/components/header';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import { Toaster } from '@/components/ui/toaster';

const PotreeRenderer = dynamic(() => import('@/components/potree-renderer'), {
	ssr: false,
});

const View: NextPage = () => {
	const session = useSession();
	const router = useRouter();

	return (
		<>
			<Head>
				<title>NTP LiDAR - View</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="h-screen">
					<Header
						title={
							<>
							NTP <span className="text-success">LiDAR</span>
							</>
						}
						session={session.data}
					/>
					<Toaster/>
				<div className="container flex flex-col items-center justify-center p-10">
					<div className="mb-4 flex w-full flex-row items-center gap-4 text-left text-2xl font-medium">
						<h2>Scan Name Here</h2>
					</div>
					<div className="grid w-full grid-cols-1 gap-4 lg:grid-cols-6 lg:grid-rows-2">
						<Canvas id="potree-canvas" className="relative row-span-2 h-[500px] overflow-hidden rounded-md lg:col-span-4 lg:h-[505px]">
							<PotreeRenderer />
						</Canvas>
						<PotreeDetails/>
					</div>
				</div>
			</main>
		</>
	);
};

export default View;
