import Head from 'next/head';
import { NextPage } from 'next';
import dynamic from 'next/dynamic';
import { Canvas } from '@react-three/fiber';
import { LiDARDetails } from '@/components/lidar-details';
import Header from '@/components/header';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import { Toaster } from '@/components/ui/toaster';
import { api } from '@/utils/api';
import { Skeleton } from '@/components/ui/skeleton';

const PotreeRenderer = dynamic(() => import('@/components/potree-renderer'), {
	ssr: false,
});

const View: NextPage = () => {
	const session = useSession();
	const router = useRouter();
	const scan = api.scans.getPublic.useQuery({
		id: (router.query.id as string) || '',
	});

	if (!scan.data || scan.isLoading || !scan.data?.scan_location) {
		return (
			<>
				<Head>
					<title>NTP LiDAR - View</title>
					<meta name="description" content="Generated by create-t3-app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className="h-screen">
					<Header
						title={
							<>
								NTP <span className="text-success">LiDAR</span>
							</>
						}
						session={session.data}
					/>
					<Toaster />
					<div className="h-screen w-screen">
						<div className="grid lg:grid-cols-4">
							<div className="col-span-3 border-2 border-white">
								<Skeleton className='h-48' />
							</div>
							<div>
								<Skeleton />
							</div>
						</div>
					</div>
				</main>
			</>
		);
	}

	return (
		<>
			<Head>
				<title>NTP LiDAR - View</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="h-screen">
				<Header
					title={
						<>
							NTP <span className="text-success">LiDAR</span>
						</>
					}
					session={session.data}
				/>
				<Toaster />
				<div className="h-screen w-screen">
					<div className="grid lg:grid-cols-4">
						<div className="col-span-3 border-2 border-white">
							<Canvas>
								<PotreeRenderer scan_location={scan.data?.scan_location} />
							</Canvas>
						</div>
						<div>
							<LiDARDetails />
						</div>
					</div>
				</div>
			</main>
		</>
	);
};

export default View;
